version: "3"
services:
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    command: bin/rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./contacts_app:/contacts_app
    ports:
      - "3000:3000"
    links:
      - db
